server:
  port: 8100
  shutdown: graceful

logging:
  config: classpath:log4j2-local.xml
  level:
    org.springframework.cloud.gateway: trace
    reactor.netty: trace

management:
  server:
    base-path: /
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
      path-mapping:
        health: /health

spring:
  cloud:
    gateway:
      routes:
        - id: netty-microservice
          uri: http://localhost:8080/
          predicates:
            - Path=/v1/**
          filters:
            - AuthorizationFilter